import Head from "next/head";
import React from "react";
import { ThemeProvider } from "../context/ThemeContext";
import { Provider } from "react-redux";
import { store } from "../store/store";
import App from "../App";
import ErrorBoundary from "../components/ErrorBoundary/ErrorBoundary.tsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <React.StrictMode>
        <ThemeProvider>
          <Provider store={store}>
            <ErrorBoundary fallback={<p>Something went wrong...</p>}>
              <App />
            </ErrorBoundary>
          </Provider>
        </ThemeProvider>
      </React.StrictMode>
    </>
  );
}
